/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esbam.canoa123.views;

import java.awt.image.BufferedImage;

/**
 *
 * @author ACER
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    java.sql.Connection con;
    
    public TelaPrincipal() {
        initComponents();
        executarComp();
        inicializa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImgBanco = new javax.swing.JLabel();
        barMenus = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnResgistro = new javax.swing.JMenuItem();
        mnInfor = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        barMenus.setBackground(new java.awt.Color(4, 81, 65));
        barMenus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        barMenus.setBorderPainted(false);

        jMenu1.setForeground(new java.awt.Color(19, 202, 202));
        jMenu1.setText("Registro");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("DokChampa", 1, 14)); // NOI18N

        mnResgistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnResgistro.setText("Registrar");
        mnResgistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnResgistroActionPerformed(evt);
            }
        });
        jMenu1.add(mnResgistro);

        barMenus.add(jMenu1);

        mnInfor.setForeground(new java.awt.Color(19, 202, 202));
        mnInfor.setText("Informação");
        mnInfor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnInfor.setFont(new java.awt.Font("DokChampa", 1, 14)); // NOI18N
        barMenus.add(mnInfor);

        jMenu2.setForeground(new java.awt.Color(19, 202, 202));
        jMenu2.setText("Marcado");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("DokChampa", 1, 14)); // NOI18N
        barMenus.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(19, 202, 202));
        jMenu3.setText("Viagem futura");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("DokChampa", 1, 14)); // NOI18N
        barMenus.add(jMenu3);

        setJMenuBar(barMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(lblImgBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnResgistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnResgistroActionPerformed
        TelaDeRegistro tableReg = new TelaDeRegistro();
        this.dispose();
        tableReg.setVisible(true);
    }//GEN-LAST:event_mnResgistroActionPerformed

    private void executarComp(){
        setSize( 420, 320);
        setResizable(false);
    }
    
    private void inicializa(){
        con = esbam.canoa123.controll.DAO.ConnectionMVC.getConnetion();
        
        if(verificaBancoDeDados(con)){
            lblImgBanco.setIcon(new javax.swing.ImageIcon(altDimen("bancoPositivo")));
        }else{
            lblImgBanco.setIcon(new javax.swing.ImageIcon(altDimen("bancoNegativo")));
        }
    }
    
    private java.awt.Image altDimen(String nomeImg){
        
        BufferedImage img = null;
        
        try{
            img = javax.imageio.ImageIO.read(new java.io.File(String.format
            ("C:\\Projetos\\123Canoa\\canoa123\\src\\main\\java\\esbam\\canoa123\\img\\%s.png", nomeImg)));
        }catch(java.io.IOException ex){
            ex.printStackTrace();
        }
        
        java.awt.Image imageDimensionada = img.getScaledInstance
        (lblImgBanco.getWidth() - 5, lblImgBanco.getHeight() - 5, java.awt.Image.SCALE_SMOOTH);
                    
        return imageDimensionada;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> { 
            new TelaPrincipal().setVisible(true); 
        });
    }
    
    private static boolean verificaBancoDeDados(java.sql.Connection conn){
        if(conn != null){
            return true;
        }else{
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenus;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JLabel lblImgBanco;
    private javax.swing.JMenu mnInfor;
    private javax.swing.JMenuItem mnResgistro;
    // End of variables declaration//GEN-END:variables
}
